Diplom2
moiseenko-e/QA-java-diplom-2 pull request #1
Opened 2023-06-24 19:22 UTC by moiseenko-e

2023-06-26 13:53 UTC, pavel-ulan requested changes
Хорошо. Все проверки, есть структурированность, хотя местами некоторые тесты смотрятся нелогично.
Но самый важный момент - наименование шагов-проверок. Это надо исправить, обязательно.

2023-06-26 13:53 UTC, pavel-ulan commented on src/main/java/praktikum/BaseDate.java
> +public class BaseDate {
Вероятно имелось в виду BaseData?

2023-06-26 13:53 UTC, pavel-ulan commented on src/main/java/praktikum/Methods.java
> +    public void createUserCorrect(ValidatableResponse response, int code, Boolean status) {
**надо исправить**
Смотри, у тебя все проверки обернуты в методы (это ок, так можно и делают), но названия этих методов не всегда понятны. Условно createUserCorrect я понимаю как СоздатьВалидногоПользователя, хотя у тебя это скорее ПроверитьКодОтветаПроСозданииВалидногоПользователя.
А вообще при таком подходе пользуйся правилом: в имени метода должны фигурировать слова check или test. Тогда и понятнее, что это обертка проверки и некоторые системы отчета используют проверку по неймингу и для них важно что бы в имени метода были эти слова.
Это может показаться не так важно, но на самом деле это довольно критичный момент. Можно допускать ошибки в нейминге и чаще всего это влият только на читабельность. Но ошибки в нейминге для методов оберток над assertами могут привести к неправильной работе.

2023-06-26 13:53 UTC, pavel-ulan commented on src/main/java/praktikum/Steps.java
> +        return given().spec(getSpec()).when().body("{\n\"ingredients\": [\"61c0c5a71d1f82001bdaaa6d\",\"61c0c5a71d1f82001bdaaa6f\",\"61c0c5a71d1f82001bdaaa74\"]\n}").post(CREATE_ORDER_ENDPOINT).then(
**можно лучше**
Я думаю ты понимаешь, что это не самый красивый вид в котором можно передать данные =)
В общем в body на самом деле можно положить много чего. Map отлично подходит, Json данные, а так же туда можно спокойно положить объект (просто надо прикрутить маршаллер) и он отлично будет работать и вид будет более чем подходящий.

2023-06-29 07:03 UTC, moiseenko-e commented on src/main/java/praktikum/BaseDate.java
> +public class BaseDate {
исправила

2023-06-29 07:04 UTC, moiseenko-e commented on src/main/java/praktikum/Methods.java
> +    public void createUserCorrect(ValidatableResponse response, int code, Boolean status) {
исправила

2023-07-13 08:54 UTC, merged